### PR TITLE
[refactor] reorder and comment events

### PR DESCRIPTION
**Pull request by kalikaneko**
Reorder blocks of events, and comment about which user-specific info
it's being emitted with them.

### CODE REVIEW

**Comment by kalikaneko** [comment]
Related to the following PRs: 
https://github.com/leapcode/soledad/pull/299
https://github.com/leapcode/leap_mail/pull/213
https://github.com/leapcode/bitmask_client/pull/954

must be merged together.

**Comment by bwagnerr** [comment]
Hey, I was taking a look and I didn't like the idea of having different user information for different signals, I know that in practice currently we don't have all the user information in all places, but I feel like we should have it. Using the user id for everything would make treating signals predictable and would also make all the code more aware of users. What do you think?

**Comment by kalikaneko** [comment]
yeah, I was also thinking about a bit more homogeneity.
everything except soledad uses the user-id (username@provider).
soledad emits the uuid, which I think it's more correct, since it identifies univocally a local replica.

I think a compromise could be to emit a dict {'userid': xxx, 'uuid': xxx} and decode it to a SoledadUser object in the receiving side. what do you think?

**Comment by bwagnerr** [comment]
I don't like the idea of the uuid (because it is different for different runs, even for the same user), personally I would go for the user-id in that case. Also uuid is specific to the soledad implementation, it would be harder to get that info to reach the other libraries in a clean manner. Maybe make soledad associate the userid to its uuid too?

I think we'll inevitably get to the idea of a user class, but we have too many levels of indirection that are directly dependent now, I was just fighting to run soledad standalone to test some cases here, and it is not really convenient. I was thinking of a better way to do this overall and I think the first step is standardizing on one field (probably user id in this case) and later on we can start making the services more independent, not to be able to run them standalone per se, but to have them intentionally they'll be less entangled that way and have clearer separations. When that turns true then I see a soledad user class being feasible.

**Comment by kalikaneko** [comment]
bwagner: ok, I think if nobody objects to that we can do the change. I think we're not using the soledad events too much yet so nothing will break.
However, what I was suggesting I think it's not incompatible:
emitting both parameters, either as different strings or serialized, and on the receiving side you can just ignore uuid.

Secondarily, this is a topic I'm struggling right now with in the bitmask-core service. When bootstrapping the sqlcipher local storage, there's no authoritative mapping from user-id to uuid. How are you dealing with that in the pixelated UA?

My current plans include keeping a hashed mapping accessible to the authorization service, so that any conversion from userid<>uuid is possible. I guess that will help with the events too.

> (because it is different for different runs, even for the same user), 

hmm. I don't think that's correct. once the account is created, the uuid will remain the same for the user.

**Comment by bwagnerr** [comment]
@kalikaneko thanks for the clarification.

We are not dealing with that in Pixelated, we don't use uuid at all.

**Comment by fbernitt** [comment]
Hey,

just to add on that, isn't there a uuid, that uniqly identifies a user? I thought there is a unique one that is used internally? Or is that one just available on the server side?

As the events occur within a running client (either bitmask or pixelated), they should be unique for the current session. The events are only valid in this unlocked context and it would be hard to act on an event for a user that is not logged in when handling it. Personaly I would prefer an ID that identifies the current session in some way. I would consider the email address a derived information here.

**Comment by kalikaneko** [comment]
> We are not dealing with that in Pixelated, we don't use uuid at all.

hum... sure? because you need the uuid to start the sqlcipher database for soledad. I guess you're just waiting until you do the srp authentication and you get it from there?

>  I would prefer an ID that identifies the current session in some way. I would consider the email address a derived information here.

interesting, I had not thought about it. This is something that Bonafide would be able to do, since we'll have the concept of session in there. what advantages do you see on a session-based indexing for events? I'm not clear if that session will be related to a remote-authentication session (based on the token maybe?) or a local unlock one (over sqlcipher).

**Comment by fbernitt** [comment]
Ah, should have connected the two a little bit more. The uuid could be that thing that identifies a session. That might be based on my past experiences, but I expected email addresses/usernames to be something that could change. If there is no unique id that could identify the user, then I would prefer the ID that identifies the current login-session as a kind of makeshift ID.

**Comment by kalikaneko** [comment]
>  If there is no unique id that could identify the user

in the case of the LEAP platform, I believe the uuid is biunivocally associated with userid. I have implemented a usermap in the incipient bitmask.core

I just realized that we're not passing user-id to Soledad initialization, so any change that expects it will be backwards-incompatible with previous soledad versions.
I'll discuss this a bit more in the soledad PR

**Comment by kalikaneko** [comment]
updated leapcode/soledad#299 so that Soledad gets userid on initialization too (but as an optional parameter, to avoid compatibility issues).
assigning to @meskio for review and merge.

**Pull request merged**
