### PR TITLE
added cryptography and some missing requirements

### PR DESCRIPTION
**Pull request by tuliocasagrande**
Cryptography was added to the code but was missing from
requirements, cffi and enum were needed by cryptography
but not required explicitly by it.

Dirspec is needed but was not on the requirements, added
launchpad url because it is not on pip anymore.

### CODE REVIEW

**Comment by kalikaneko** [comment]
I don't see where cryptography is used in leap.common, mind to point me to it?

**Comment by kalikaneko** [comment]
maybe you intended to add this to soledad.client?

**Comment by kalikaneko** [comment]
apart from where cryptography is missing, I don't understand why its deps have to be explicitely added, see:
```
ollecting cryptography
  Downloading cryptography-1.2.3.tar.gz (373kB)
    100% |████████████████████████████████| 378kB 86kB/s 
Collecting idna>=2.0 (from cryptography)
  Using cached idna-2.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting six>=1.4.1 (from cryptography)
  Using cached six-1.10.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools>=1.0 in /home/kali/Virtualenvs/crypto-pyinst-bug/lib/python2.7/site-packages (from cryptography)
Collecting enum34 (from cryptography)
Collecting ipaddress (from cryptography)
  Using cached ipaddress-1.0.16-py27-none-any.whl
Collecting cffi>=1.4.1 (from cryptography)
Collecting pycparser (from cffi>=1.4.1->cryptography)
Building wheels for collected packages: cryptography
  Running setup.py bdist_wheel for cryptography ... 
done
  Stored in directory: /home/kali/.cache/pip/wheels/7f/53/82/7d953f200e270b2832bc8632771f6ddc8e2985ea7773202dab
Successfully built cryptography
Installing collected packages: idna, pyasn1, six, enum34, ipaddress, pycparser, cffi, cryptography
Successfully installed cffi-1.5.2 cryptography-1.2.3 enum34-1.1.2 idna-2.0 ipaddress-1.0.16 pyasn1-0.1.9 pycparser-2.14 six-1.10.0
```

**Comment by kalikaneko** [comment]
this can be closed right? send a new one with the dirspec fix maybe

**Comment by tuliocasagrande** [comment]
Sure, Kali. You can close it.

I don't know why my machine was asking for cryptography and the other requirements. But now it's not doing anymore.

Thanks!!! :D

**Pull request closed without merging**
