### PR TITLE
[feature] allow passing callback to http client

### PR DESCRIPTION
**Pull request by andrejb**
May be merged.

### CODE REVIEW

**Comment by bwagnerr** [comment]
@kalikaneko
1. Even if you check what would you do after? It you try to call it, it will explode, if you check if it's callable and it isn't, the only option I see is to explode, so I don't see a need for this.
2. Not sure, it doesn't even have to return anything, it has flexibility to do what it wants with the body of the response
3. About usage, http_target had a different readBody and is explicitly passing it to the client.

**Comment by kalikaneko** [comment]
1. I think it's good practice to fail with a meaningful error
2. Do we have guarantees that this will be the last callback in the chain?

**Comment by bwagnerr** [comment]
1. The error in that case would be TypeError: '<type>' object is not callable, I thought that was clear enough
2. Maybe we should make sure it always returns the response body no matter what it does with it? That is what makes sense to me anyway.

**Comment by kalikaneko** [comment]
1. it depends on what you consider clear hehe.
for sure it will crash, and it will raise an exception, but all the same I think it's good to be defensive.
just grep twisted code for 
```assert callable(f), "%s is not callable" % (f,)```

the issue here is about where to put the responsibility of validating (somehow) the inputs. I prefer a stacktrace that shows a function in a code that we control, since it's quicker to arrive to that un-winding a callback chain if the error is raised in twisted code.

2. sounds good. that's something the docstring could document, that all callbacks are expected to return the body (or whatever).

**Pull request merged**
